default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: postgres
    password: 4976
    host: localhost
    port: 5432

development:
    <<: *default
    database: ror_blog-v5_development

test:
    <<: *default
    database: ror_blog-v5_test

production:
    <<: *default
    database: ror_blog-v5_production
    username: postgres
    password: <%= ENV['BLOG_APP_DATABASE_PASSWORD'] %>
